name: Build socat for MIPSel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            libssl-dev \
            gcc-mipsel-linux-gnu \
            g++-mipsel-linux-gnu \
            binutils-mipsel-linux-gnu \
            libc6-dev-mipsel-cross \
            libgcc-mipsel-linux-gnu-dev \
            linux-libc-dev-mipsel-cross \
            libstdc++6-mipsel-cross \
            libgcc1-mipsel-cross \
            libc6-mipsel-cross
          # Verify compiler and library paths
          mipsel-linux-gnu-gcc --version || echo "Compiler not found"
          ls -l /usr/mipsel-linux-gnu/lib || echo "Library path not found"
          ls -l /usr/mipsel-linux-gnu/include || echo "Include path not found"

      - name: Download and extract socat
        run: |
          wget http://www.dest-unreach.org/socat/download/socat-1.7.4.4.tar.gz
          tar -xzf socat-1.7.4.4.tar.gz
          mv socat-1.7.4.4 socat

      - name: Test compiler
        run: |
          echo "int main() { return 0; }" > test.c
          mipsel-linux-gnu-gcc -o test test.c -I/usr/mipsel-linux-gnu/include -L/usr/mipsel-linux-gnu/lib || echo "Compiler test failed"

      - name: Configure socat for mipsel
        run: |
          cd socat
          ./configure \
            CC=mipsel-linux-gnu-gcc \
            CXX=mipsel-linux-gnu-g++ \
            --host=mipsel-linux-gnu \
            --build=x86_64-linux-gnu \
            --prefix=$PWD/install
        env:
          CFLAGS: "-O2"
          CXXFLAGS: "-O2"
          LDFLAGS: "-L/usr/mipsel-linux-gnu/lib"
          CPPFLAGS: "-I/usr/mipsel-linux-gnu/include"
          PKG_CONFIG_PATH: "/usr/mipsel-linux-gnu/lib/pkgconfig"

      - name: Check build environment
        run: |
          echo "Disk space:"
          df -h
          echo "Memory usage:"
          free -m
          echo "CPU info:"
          lscpu
          echo "Running processes:"
          ps aux

      - name: Build socat with progress monitoring
        timeout-minutes: 15
        run: |
          cd socat
          # Script to monitor build progress and log output
          echo "Starting build with verbose output..."
          {
            make V=1 -j1 | while read -r line; do
              echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') $line"
              # Reset inactivity timer on each line
            done
          } 2>&1 | tee build.log
          # Check if build completed successfully
          if [ ! -f socat ]; then
            echo "Build failed: socat binary not found"
            exit 1
          fi

      - name: Debug build failure
        if: failure()
        run: |
          echo "Build failed. Printing build.log"
          cat socat/build.log || true
          echo "Listing generated files"
          find socat -type f || true
          echo "Last few lines of build.log:"
          tail -n 20 socat/build.log || true

      - name: Install socat
        run: |
          cd socat
          make install

      - name: Package binary
        run: |
          mkdir -p artifacts
          cp socat/install/bin/socat artifacts/socat-mipsel
          tar -czf socat-mipsel.tar.gz -C artifacts socat-mipsel

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: socat-mipsel
          path: socat-mipsel.tar.gz
          retention-days: 7
