name: Build socat for Multiple Architectures

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - name: x86
            target: i686-linux-gnu
            cc: gcc
            cxx: g++
            extra_flags: ""
            is_cross: false
            lib_path: /usr/lib
            include_path: /usr/include
          - name: x64
            target: x86_64-linux-gnu
            cc: gcc
            cxx: g++
            extra_flags: ""
            is_cross: false
            lib_path: /usr/lib
            include_path: /usr/include
          - name: armv6
            target: arm-linux-gnueabi
            cc: arm-linux-gnueabi-gcc
            cxx: arm-linux-gnueabi-g++
            extra_flags: "--host=arm-linux-gnueabi --build=x86_64-linux-gnu"
            is_cross: true
            lib_path: /usr/arm-linux-gnueabi/lib
            include_path: /usr/arm-linux-gnueabi/include
          - name: mips
            target: mips-linux-gnu
            cc: mips-linux-gnu-gcc
            cxx: mips-linux-gnu-g++
            extra_flags: "--host=mips-linux-gnu --build=x86_64-linux-gnu"
            is_cross: true
            lib_path: /usr/mips-linux-gnu/lib
            include_path: /usr/mips-linux-gnu/include

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          if [ "${{ matrix.arch.is_cross }}" = "true" ]; then
            sudo apt-get install -y \
              build-essential \
              autoconf \
              automake \
              libtool \
              libssl-dev \
              gcc-${{ matrix.arch.target }} \
              g++-${{ matrix.arch.target }} \
              binutils-${{ matrix.arch.target }} \
              libc6-dev-${{ matrix.arch.target }}-cross \
              libgcc-${{ matrix.arch.target }}-dev \
              linux-libc-dev-${{ matrix.arch.target }}-cross \
              libstdc++6-${{ matrix.arch.target }}-cross || true
          else
            sudo apt-get install -y \
              build-essential \
              autoconf \
              automake \
              libtool \
              libssl-dev \
              gcc \
              g++ \
              libc6-dev \
              libgcc-13-dev \
              linux-libc-dev \
              libstdc++6 || true
          fi
          # Verify compiler and library paths
          ${{ matrix.arch.cc }} --version || echo "Compiler not found"
          ls -l ${{ matrix.arch.lib_path }} || echo "Library path not found"
          ls -l ${{ matrix.arch.include_path }} || echo "Include path not found"

      - name: Download and extract socat
        run: |
          wget http://www.dest-unreach.org/socat/download/socat-1.7.4.4.tar.gz
          tar -xzf socat-1.7.4.4.tar.gz
          mv socat-1.7.4.4 socat

      - name: Test compiler
        run: |
          echo "int main() { return 0; }" > test.c
          ${{ matrix.arch.cc }} -o test test.c -I${{ matrix.arch.include_path }} -L${{ matrix.arch.lib_path }} || echo "Compiler test failed"

      - name: Configure socat for ${{ matrix.arch.name }}
        run: |
          cd socat
          ./configure \
            CC=${{ matrix.arch.cc }} \
            CXX=${{ matrix.arch.cxx }} \
            ${{ matrix.arch.extra_flags }} \
            --prefix=$PWD/install
        env:
          CFLAGS: "-O2"
          CXXFLAGS: "-O2"
          LDFLAGS: "-L${{ matrix.arch.lib_path }}"
          CPPFLAGS: "-I${{ matrix.arch.include_path }}"

      - name: Debug configure failure
        if: failure()
        run: |
          echo "Configure failed. Printing config.log for ${{ matrix.arch.name }}"
          cat socat/config.log || true
          echo "Listing library and include paths"
          find ${{ matrix.arch.lib_path }} -type f || true
          find ${{ matrix.arch.include_path }} -type f || true

      - name: Build socat
        run: |
          cd socat
          make -j$(nproc)

      - name: Install socat
        run: |
          cd socat
          make install

      - name: Package binary
        run: |
          mkdir -p artifacts
          cp socat/install/bin/socat artifacts/socat-${{ matrix.arch.name }}
          tar -czf socat-${{ matrix.arch.name }}.tar.gz -C artifacts socat-${{ matrix.arch.name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: socat-${{ matrix.arch.name }}
          path: socat-${{ matrix.arch.name }}.tar.gz
          retention-days: 7
